INSERT INTO opportunity (employer_user_id,
                         title,
                         short_description,
                         full_description,
                         requirements,
                         company_name,
                         type,
                         work_format,
                         employment_type,
                         grade,
                         salary_from,
                         salary_to,
                         salary_currency,
                         published_at,
                         expires_at,
                         event_date,
                         city_id,
                         location_id,
                         contact_info,
                         moderation_comment,
                         status)
VALUES (2,
        'Java-разработчик (Junior)',
        'Ищем Java-разработчика для работы над платформой Трамплин',
        'Полное описание: работа в команде, разработка микросервисов, участие в проектировании. Требования: Java 17, Spring, знание SQL. Опыт от 1 года. Условия: гибкий график, ДМС, обучение.',
        'Java 17, Spring Framework, PostgreSQL, Git',
        'ООО "ИТ-Планета"',
        'VACANCY',
        'OFFICE',
        'FULL_TIME',
        'JUNIOR',
        60000,
        80000,
        'RUB',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP + INTERVAL '30 days',
        NULL,
        4,
        4,
        '{
            "email": "hr@itplanet.ru",
            "phone": "+7-495-123-45-67"
        }',
        NULL,
        'PUBLISHED');


INSERT INTO opportunity (employer_user_id,
                         title,
                         short_description,
                         full_description,
                         requirements,
                         company_name,
                         type,
                         work_format,
                         employment_type,
                         grade,
                         salary_from,
                         salary_to,
                         salary_currency,
                         published_at,
                         expires_at,
                         event_date,
                         city_id,
                         location_id,
                         contact_info,
                         moderation_comment,
                         status)
VALUES (2,
        'Python-разработчик (Middle)',
        'Ищем Python-разработчика для backend-направления',
        'Работа над высоконагруженным сервисом, интеграции, оптимизация. Требования: Python 3.10+, FastAPI, PostgreSQL, Docker. Опыт от 3 лет.',
        'Python 3.10+, FastAPI, PostgreSQL, Docker, Kubernetes',
        'АО "Цифровые Решения"',
        'VACANCY',
        'REMOTE',
        'FULL_TIME',
        'MIDDLE',
        120000,
        150000,
        'RUB',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP + INTERVAL '45 days',
        NULL,
        5,
        5,
        '{
            "email": "career@digitalsolutions.ru",
            "telegram": "@hr_digital"
        }',
        NULL,
        'PUBLISHED');