server:
  port: 8091

spring:
  application:
    name: media

  datasource:
    url: jdbc:postgresql://64.188.97.232:5432/tramplin
    username: tramplin_adm
    password: tramplin_adm

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB

springdoc:
  paths-to-match: /internal/**
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
    filter: true

storage:
  s3:
    endpoint: ${TWC_S3_ENDPOINT:https://s3.twcstorage.ru}
    region: ${TWC_S3_REGION:ru-1}
    bucket: ${TWC_S3_BUCKET:trampline-dev}
    access-key: ${TWC_S3_ACCESS_KEY:}
    secret-key: ${TWC_S3_SECRET_KEY:}
    key-prefix: ${TWC_S3_KEY_PREFIX:trampline}
    path-style-access-enabled: ${TWC_S3_PATH_STYLE:true}
    connect-timeout: ${TWC_S3_CONNECT_TIMEOUT:5s}
    read-timeout: ${TWC_S3_READ_TIMEOUT:30s}
    presigned-url-ttl: ${TWC_S3_PRESIGNED_URL_TTL:15m}

internal-api:
  api-key: moderation-api-key

media:
  cleanup:
    enabled: true
    batch-size: 50
    deleted-file-min-age: 15m
    fixed-delay: 30m
