server:
  port: ${PORT:8082}

spring:
  application:
    name: moderation

  datasource:
    url: ${PROFILE_DB_URL}
    username: ${PROFILE_DB_USERNAME}
    password: ${PROFILE_DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

auth:
  service:
    url: ${AUTH_SERVER_HOST:http://localhost:9999}

profile:
  service:
    url: ${PROFILE_SERVER_HOST:http://localhost:8080}

opportunity:
  service:
    url: ${OPPORTUNITY_SERVER_HOST:http://localhost:8081}

media:
  service:
    url: ${MEDIA_SERVER_HOST:http://localhost:8091}

internal-api:
  api-key: ${INTERNAL_API_KEY}

springdoc:
  paths-to-match: /api/**
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
    filter: true
