export const SKILLS = [
    'JavaScript',
    'TypeScript',
    'React',
    'Vue',
    'Angular',
    'Node.js',
    'Express',
    'NestJS',
    'Python',
    'Django',
    'FastAPI',
    'Java',
    'Spring',
    'C#',
    '.NET',
    'Go',
    'SQL',
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Redis',
    'Docker',
    'Kubernetes',
    'Git',
    'CI/CD',
    'HTML',
    'CSS',
    'SCSS',
    'Tailwind CSS',
    'Figma',
    'Linux',
    'REST API',
    'GraphQL',
    'Testing',
    'Jest',
    'Playwright',
    'PHP',
    'Laravel',
    'Symfony',
    'Ruby',
    'Ruby on Rails',
    'Swift',
    'Kotlin',
    'Flutter',
    'React Native',
    'Ionic',
    'C++',
    'Rust',
    'Zig',
    'Elixir',
    'Erlang',
    'Scala',
    'Clojure',
    'Haskell',
    'F#',
    'Objective-C',
    'Perl',
    'R',
    'MATLAB',
    'Julia',
    'VBA',
    'Assembly',
    'WebAssembly',
    'HTML5',
    'CSS3',
    'Sass',
    'Less',
    'PostCSS',
    'Bootstrap',
    'Material UI',
    'Ant Design',
    'Chakra UI',
    'Styled Components',
    'Emotion',
    'Redux',
    'MobX',
    'Zustand',
    'Pinia',
    'Vuex',
    'Next.js',
    'Nuxt.js',
    'Svelte',
    'SvelteKit',
    'Remix',
    'Gatsby',
    'Astro',
    'Webpack',
    'Vite',
    'Rollup',
    'Parcel',
    'Babel',
    'ESLint',
    'Prettier',
    'Husky',
    'Storybook',
    'Jira',
    'Confluence',
    'Trello',
    'Asana',
    'Notion',
    'Slack',
    'Teams',
    'Figma',
    'Sketch',
    'Adobe XD',
    'Adobe Photoshop',
    'Adobe Illustrator',
    'Adobe After Effects',
    'Blender',
    'Cinema 4D',
    'AutoCAD',
    'Revit',
    '3ds Max',
    'Maya',
    'ZBrush',
    'Framer',
    'Webflow',
    'Tilda',
    'WordPress',
    'Shopify',
    'OpenCart',
    'Magento',
    '1C-Bitrix',
    'Drupal',
    'Joomla',
    'MongoDB',
    'Cassandra',
    'DynamoDB',
    'Elasticsearch',
    'ClickHouse',
    'Oracle',
    'SQLite',
    'MariaDB',
    'Firebase',
    'Supabase',
    'Appwrite',
    'Hasura',
    'Prisma',
    'TypeORM',
    'Sequelize',
    'Knex.js',
    'RabbitMQ',
    'Kafka',
    'Apache Spark',
    'Apache Flink',
    'Hadoop',
    'Airflow',
    'dbt',
    'Tableau',
    'Power BI',
    'Looker',
    'Data Science',
    'Machine Learning',
    'Deep Learning',
    'Computer Vision',
    'NLP',
    'TensorFlow',
    'PyTorch',
    'Keras',
    'Scikit-learn',
    'Pandas',
    'NumPy',
    'Matplotlib',
    'Seaborn',
    'Plotly',
    'OpenCV',
    'Hugging Face',
    'LangChain',
    'LLM',
    'Prompt Engineering',
    'AWS',
    'Azure',
    'Google Cloud Platform',
    'Yandex Cloud',
    'SberCloud',
    'VK Cloud',
    'Terraform',
    'Ansible',
    'Puppet',
    'Chef',
    'Prometheus',
    'Grafana',
    'ELK Stack',
    'Splunk',
    'Datadog',
    'New Relic',
    'Jenkins',
    'GitLab CI',
    'GitHub Actions',
    'CircleCI',
    'Travis CI',
    'ArgoCD',
    'Helm',
    'Istio',
    'Envoy',
    'Nginx',
    'Apache',
    'Traefik',
    'HAProxy',
    'Linux',
    'Ubuntu',
    'CentOS',
    'Debian',
    'Alpine',
    'Windows Server',
    'Bash',
    'PowerShell',
    'Zsh',
    'Command Line',
    'Networking',
    'TCP/IP',
    'DNS',
    'HTTP/HTTPS',
    'WebSockets',
    'gRPC',
    'Protocol Buffers',
    'OpenAPI',
    'Swagger',
    'Postman',
    'Insomnia',
    'Selenium',
    'Cypress',
    'Puppeteer',
    'Jest',
    'Vitest',
    'Mocha',
    'Chai',
    'Cucumber',
    'Gherkin',
    'Unit Testing',
    'Integration Testing',
    'E2E Testing',
    'TDD',
    'BDD',
    'Agile',
    'Scrum',
    'Kanban',
    'SAFe',
    'Project Management',
    'Product Management',
    'Team Leadership',
    'Mentoring',
    'Technical Writing',
    'Documentation',
    'API Design',
    'System Architecture',
    'Microservices',
    'Monolith',
    'Serverless',
    'Event-Driven Architecture',
    'Domain-Driven Design',
    'Clean Architecture',
    'SOLID Principles',
    'Design Patterns',
    'Algorithms',
    'Data Structures',
    'Performance Optimization',
    'Security Best Practices',
    'OWASP',
    'Penetration Testing',
    'Code Review',
    'Refactoring',
    'Mobile Development',
    'iOS',
    'Android',
    'Cross-Platform',
    'Desktop Development',
    'Electron',
    'Tauri',
    'Qt',
    'WPF',
    'WinForms',
    'Embedded Systems',
    'Arduino',
    'Raspberry Pi',
    'IoT',
    'Firmware',
    'FPGA',
    'VHDL',
    'Verilog',
    'Game Development',
    'Unity',
    'Unreal Engine',
    'Godot',
    'Cocos2d',
    'WebGL',
    'Three.js',
    'Babylon.js',
    'WebRTC',
    'Web3',
    'Blockchain',
    'Ethereum',
    'Smart Contracts',
    'Solidity',
    'Rust',
    'Bitcoin',
    'Cryptocurrency',
    'NFT',
    'DeFi',
    'VR/AR',
    'ARCore',
    'ARKit',
    'Spatial Computing',
    'UX Design',
    'UI Design',
    'User Research',
    'Usability Testing',
    'Wireframing',
    'Prototyping',
    'Design Systems',
    'Typography',
    'Color Theory',
    'Animation',
    'Motion Design',
    'Video Editing',
    'Premiere Pro',
    'Final Cut Pro',
    'DaVinci Resolve',
    'Sound Design',
    'Audio Production',
    'SEO',
    'ASO',
    'Analytics',
    'Google Analytics',
    'Yandex Metrica',
    'Data Visualization',
    'Business Analysis',
    'Requirements Gathering',
    'Sales',
    'Negotiation',
    'Presentation Skills',
    'Communication Skills',
    'Problem Solving',
    'Critical Thinking',
    'Creativity',
    'Time Management',
    'Adaptability',
    'Teamwork',
    'Conflict Resolution',
    'Emotional Intelligence',
    'Leadership',
    'Strategic Planning',
    'Decision Making',
    'Risk Management',
    'Budgeting',
    'Financial Analysis',
    'Data Analysis',
    'Statistical Analysis',
    'A/B Testing',
    'Excel',
    'Google Sheets',
    'Jupyter Notebook',
    'Markdown',
    'LaTeX',
    'Graphic Design',
    'Motion Graphics',
    'Photography',
    'Copywriting',
    'Content Writing',
    'Editing',
    'Public Speaking',
    'Social Media Management',
    'SMM',
    'Digital Marketing',
    'Email Marketing',
    'PPC',
    'Analytical Thinking',
    'Research Skills',
    'Multitasking',
    'Attention to Detail',
    'Punctuality',
    'Responsibility'
];