spring:
  application:
    name: profile
  datasource:
    url: ${PROFILE_DB_URL:jdbc:postgresql://64.188.97.232:5432/tramplin}
    username: ${PROFILE_DB_USERNAME:tramplin_adm}
    password: ${PROFILE_DB_PASSWORD:tramplin_adm}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB

auth:
  service:
    url: ${AUTH_SERVER_HOST:http://localhost:9999}

media:
  service:
    url: ${MEDIA_SERVICE_URL:http://localhost:8091}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

internal-api:
  api-key: moderation-api-key

springdoc:
  paths-to-match: /api/**
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
    filter: true
