server:
  port: 8081

spring:
  application:
    name: opportunity

  datasource:
    url: jdbc:postgresql://64.188.97.232:5432/tramplin
    username: tramplin_adm
    password: tramplin_adm

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:9999}

moderation:
  service:
    url: ${MODERATION_SERVICE_URL:http://localhost:8082}

media:
  service:
    url: ${MEDIA_SERVICE_URL:http://localhost:8091}

internal-api:
  api-key: moderation-api-key

springdoc:
  paths-to-match: /api/**
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
    filter: true
