server:
  port: 9999

spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://64.188.97.232:5432/tramplin
    username: tramplin_adm
    password: tramplin_adm
  data:
    redis:
      host: 64.188.97.232
      port: 6379
      password: mtp_token
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

auth:
  session:
    cookie-name: sessionId
    ttl-seconds: 86400
    secure-cookie: false
    same-site: Lax

internal-api:
  api-key: moderation-api-key

springdoc:
  paths-to-match: /api/**
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
    filter: true
    csrf:
      enabled: true
      cookie-name: XSRF-TOKEN
      header-name: X-XSRF-TOKEN
